[build]
  publish = "."
  functions = "netlify/functions"

[[edge_functions]]
  function = "auth"
  path = "/*"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

